include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.chopper.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - riverpod_lint

linter:
  rules:

plugins:
  riverpod_lint: ^3.1.0
